apiVersion: v1
kind: Template
labels:
  app: freelancer-service
metadata:
  name: freelancer-postgresql
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: freelancer-service
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 5432
      targetPort: 5432
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: freelancer-service
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      recreateParams:
        post:
          execNewPod:
            command:
              - /bin/sh
              - -i
              - -c
              - sleep 10 && PGPASSWORD=$POSTGRESQL_PASSWORD psql -h $FREELANCER_POSTGRESQL_SERVICE_HOST -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c "$POSTGRESQL_INIT"
            containerName: ${APPLICATION_NAME}
            env:
            - name: POSTGRESQL_INIT
              value: CREATE TABLE FREELANCER( FREELANCER_ID BIGINT NOT NULL, EMAIL_ADDRESS VARCHAR(255), FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255) ); 
                     CREATE TABLE FREELANCER_SKILLS( FREELANCER_FREELANCER_ID BIGINT NOT NULL, SKILLS VARCHAR(255) );
                     CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1;
                     ALTER TABLE FREELANCER OWNER TO jboss;
                     ALTER TABLE FREELANCER_SKILLS OWNER TO jboss;
                     ALTER SEQUENCE HIBERNATE_SEQUENCE OWNER TO jboss;
                     ALTER TABLE FREELANCER ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(FREELANCER_ID);
                     ALTER TABLE FREELANCER_SKILLS ADD CONSTRAINT FKL28OEU5AKV61A916CHE7D6VMR FOREIGN KEY(FREELANCER_FREELANCER_ID) REFERENCES FREELANCER(FREELANCER_ID);
                     INSERT INTO FREELANCER VALUES(1, 'agiertli@redhat.com', 'Anton', 'Giertli');
                     INSERT INTO FREELANCER_SKILLS VALUES (1,'Java');
                     INSERT INTO FREELANCER_SKILLS VALUES (1,'OpenShift basic');
                     INSERT INTO FREELANCER_SKILLS VALUES (1,'Development');
                     INSERT INTO FREELANCER VALUES(2, 'cdarby@redhat.com', 'Chad', 'Darby');
                     INSERT INTO FREELANCER_SKILLS VALUES (2,'Teaching');
                     INSERT INTO FREELANCER_SKILLS VALUES (2,'OpenShift advanced');
                     INSERT INTO FREELANCER_SKILLS VALUES (2,'Java');
          failurePolicy: ignore
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: freelancer-service
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: ${FREELANCER_DB_USERNAME}
          - name: POSTGRESQL_PASSWORD
            value: ${FREELANCER_DB_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: ${FREELANCER_DB_NAME}
          image: postgresql
          imagePullPolicy: IfNotPresent
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 5432
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: freelancer-postgresql-data
          livenessProbe:
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 10
            tcpSocket:
              port: 5432
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            failureThreshold: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
        terminationGracePeriodSeconds: 60
        volumes:
        - name: freelancer-postgresql-data
          persistentVolumeClaim:
            claimName: freelancer-postgresql-pv
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: postgresql:latest
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: freelancer-service
    name: freelancer-postgresql-pv
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
parameters:
- description: Application name
  name: APPLICATION_NAME
  required: true
  value: freelancer-postgresql
- description: freelancer Service database user name
  from: user[a-zA-Z0-9]{3}
  generate: expression
  name: FREELANCER_DB_USERNAME
  required: true
- description: freelancer Service database user password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: FREELANCER_DB_PASSWORD
  required: true
- description: freelancer Service database name
  name: FREELANCER_DB_NAME
  required: true
  value: freelancerdb